name: 'Tests'

on:
  push:
    branches:
      - master
      - develop
      - test-check
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        working-directory: ./application/client
        run: npm install