name: 'Tests'

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  lint-nuxt:
    name: 'lint (node: ${{ matrix.node }})'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
      - uses: ./.github/actions/install-modules
      - name: cd
        run: cd ./application/client
      - name: Run lint
        run: npm run -s lint